[package]
name = "photolib"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
ini = "1.3.0"
regex = "1.10.5"
rexiv2 = "0.10.0"
sqlite = "0.36.0"
xdg = "2.5.2"
xmp_toolkit = "1.9.0"
